name: vorq

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vorq
      POSTGRES_PASSWORD: vorq
      POSTGRES_DB: vorq
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
